In [1]:
import numpy as np
import sys

# 1D array methods

In [2]:
array = np.array([1, 2, 3])

In [3]:
sys.getsizeof(array[2])

32

In [4]:
array2 = np.linspace(0., 20., 5)
array2.dtype

dtype('float64')

In [5]:
array3 =np.linspace(0., 20., 5, dtype=int)
print(array3)
array3.dtype

[ 0  5 10 15 20]


dtype('int64')

In [6]:
array[2]

3

In [7]:
sys.getsizeof(array[2])

32

In [8]:
array2[1:-1]

array([ 5., 10., 15.])

In [9]:
array+array2

ValueError: operands could not be broadcast together with shapes (3,) (5,) 

In [10]:
array2*3

array([ 0., 15., 30., 45., 60.])

# 2D array operations

In [12]:
array4 = np.array([[0, 1, 2], [4, 5, 6]])
array4

array([[0, 1, 2],
       [4, 5, 6]])

In [13]:
print(array4[1][0])
print(array4[1, 0])

4
4


In [14]:
num_rows, num_cols = array4.shape #returns a tuple
print("Shape of array4 is", (num_rows, num_cols))

Shape of array4 is (2, 3)


## Meshgrid

In [17]:
num_rows = 5 
num_cols = 3
x_coords = np.linspace(0, num_cols - 1, num_cols)
y_coords = np.linspace(0, num_rows - 1, num_rows)
print("x coordinates are", x_coords)
print("y coordinates are", y_coords)

x_grid, y_grid = np.meshgrid(x_coords, y_coords)
print("Grid of x coordinates is\n", x_grid)
print("Grid of y coordinates is\n", y_grid)

x coordinates are [0. 1. 2.]
y coordinates are [0. 1. 2. 3. 4.]
Grid of x coordinates is
 [[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]]
Grid of y coordinates is
 [[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]
 [4. 4. 4.]]


In [18]:
print("(x, y) position of array[1, 0] is", x_grid[1, 0], y_grid[1, 0])

(x, y) position of array[1, 0] is 0.0 1.0
